#!/bin/bash
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS
# FOR A PARTICULAR PURPOSE. THIS CODE AND INFORMATION ARE NOT SUPPORTED BY XEBIALABS.
#

echo "Performing a Datastage UnDeployment"

echo "Undeploying using /bin/UNDEPLOYSCRIPT -undeploy -project ${previousDeployed.deploymentDSProject} -job ${previousDeployed.deploymentDSJob}"

echo "NOT WORKING YET"